# Generated by Django 3.2 on 2022-08-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status_reservation',
            field=models.CharField(choices=[('cancel', 'cancel'), ('reserve', 'reserve'), ('reserved', 'reserved'), ('free', 'free')], max_length=27),
        ),
    ]
