# Generated by Django 3.2 on 2022-08-15 07:46

from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.user')),
                ('full_name', models.CharField(max_length=80)),
                ('medical_system_code', models.IntegerField()),
                ('adress', models.TextField()),
                ('registeration_date', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField()),
                ('cost_visit', models.PositiveBigIntegerField(default=10000)),
                ('visit_time', models.CharField(choices=[('15', '15 mine'), ('20', '20 mine'), ('30', '30 mine'), ('45', '45 mine'), ('60', '60 mine'), ('90', '90 mine'), ('120', '120 mine')], max_length=10)),
                ('doctor_specilist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorspecialist')),
            ],
            options={
                'abstract': False,
            },
            bases=('patients.user',),
            managers=[
                ('objects', patients.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.PositiveBigIntegerField(unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser')),
            ],
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='week_days',
            field=models.ManyToManyField(to='doctors.WeekDays'),
        ),
        migrations.AddField(
            model_name='doctorspecialist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorspecialist'),
        ),
        migrations.AddField(
            model_name='doctorshift',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser'),
        ),
        migrations.AddField(
            model_name='doctorexperoence',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser'),
        ),
        migrations.AddField(
            model_name='commentfordoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser'),
        ),
        migrations.AddField(
            model_name='commentfordoctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
