# Generated by Django 3.2 on 2022-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='cost_visit',
            field=models.PositiveBigIntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='medical_system_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='registeration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='visit_time',
            field=models.CharField(blank=True, choices=[('15', '15 mine'), ('20', '20 mine'), ('30', '30 mine'), ('45', '45 mine'), ('60', '60 mine'), ('90', '90 mine'), ('120', '120 mine')], max_length=10, null=True),
        ),
    ]
