# Generated by Django 3.2 on 2022-08-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20220815_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='doctor_specilist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorspecialist'),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='week_days',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.WeekDays'),
        ),
    ]
