# Generated by Django 3.2 on 2022-08-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20220815_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='week_days',
        ),
        migrations.AddField(
            model_name='weekdays',
            name='week_days',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.DoctorUser'),
        ),
    ]
