# Generated by Django 4.0.4 on 2022-08-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_auto_20220815_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorshift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctorshift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
