# Generated by Django 4.0.4 on 2022-08-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctorshift_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekdays',
            old_name='week_days',
            new_name='doctor',
        ),
    ]
