# Generated by Django 4.0.4 on 2022-08-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_commentfordoctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorexperoence',
            name='experoence',
            field=models.IntegerField(),
        ),
    ]
