# Generated by Django 4.0.4 on 2022-08-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctorexperoence_experoence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorexperoence',
            old_name='experoence',
            new_name='experience',
        ),
    ]
