# Generated by Django 4.0.4 on 2022-08-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_rename_experoence_doctorexperoence_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorexperoence',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser'),
        ),
    ]
