# Generated by Django 4.0.4 on 2022-08-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_alter_doctorexperoence_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorexperoence',
            old_name='experience',
            new_name='years_experience',
        ),
        migrations.AddField(
            model_name='doctorexperoence',
            name='loction',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorexperoence',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser'),
        ),
    ]
