# Generated by Django 4.0.4 on 2022-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_rename_experience_doctorexperoence_years_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruser',
            name='Gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='city',
            field=models.CharField(blank=True, choices=[('Tehran', 'Tehran'), ('Esfahan', 'Esfahan'), ('Shiraz', 'Shiraz'), ('Tabriz', 'Tabriz'), ('Gilan', 'Gilan'), ('Khoozestan', 'Khoozestan')], max_length=50, null=True),
        ),
    ]
