# Generated by Django 4.0.4 on 2022-08-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_doctoruser_gender_doctoruser_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoruser',
            old_name='Gender',
            new_name='gender',
        ),
    ]
