# Generated by Django 4.0.4 on 2022-08-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_alter_doctoruser_city_delete_doctorcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorcity')),
            ],
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorcity'),
        ),
    ]
