# Generated by Django 4.0.4 on 2022-08-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_rename_name_city_doctorcity_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='visit_time',
            field=models.CharField(blank=True, choices=[('15', '15 mine'), ('20', '20 mine'), ('25', '25 mine'), ('30', '30 mine'), ('45', '45 mine'), ('50', '50 mine'), ('60', '60 mine'), ('80', '80 mine'), ('90', '90 mine'), ('100', '100 mine'), ('120', '120 mine')], max_length=10, null=True),
        ),
    ]
