# Generated by Django 4.0.4 on 2022-08-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_alter_doctoruser_visit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='adress',
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='doctors.doctoruser'),
        ),
        migrations.CreateModel(
            name='DoctorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser')),
            ],
        ),
    ]
