# Generated by Django 4.0.4 on 2022-08-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0022_remove_doctoruser_adress_alter_weekdays_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoraddress',
            old_name='adress',
            new_name='address',
        ),
    ]
