# Generated by Django 4.0.4 on 2022-08-19 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_rename_adress_doctoraddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoraddress',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser'),
        ),
    ]
