# Generated by Django 4.0.4 on 2022-08-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0024_alter_doctoraddress_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoraddress',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctoruser'),
        ),
    ]
