# Generated by Django 4.0.4 on 2022-08-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_alter_doctoraddress_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoruser',
            old_name='doctor_specilist',
            new_name='doctor_specialist',
        ),
    ]
