# Generated by Django 4.0.4 on 2022-08-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0027_rename_doctor_specilist_doctoruser_doctor_specialist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorspecialist',
            old_name='specialist',
            new_name='specilist',
        ),
        migrations.AddField(
            model_name='weekdays',
            name='shift',
            field=models.ManyToManyField(to='doctors.doctorshift'),
        ),
    ]
