# Generated by Django 4.0.4 on 2022-08-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0029_rename_specilist_doctorspecialist_specialist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorspecialist',
            old_name='specialist',
            new_name='specilist',
        ),
    ]
