# Generated by Django 4.0.4 on 2022-08-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0030_rename_specialist_doctorspecialist_specilist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorspecialist',
            old_name='specilist',
            new_name='specialist',
        ),
    ]
