# Generated by Django 4.0.4 on 2022-08-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0032_alter_weekdays_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='day',
            field=models.ManyToManyField(blank=True, to='doctors.weekdays'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day',
            field=models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=10),
        ),
    ]
