# Generated by Django 4.0.4 on 2022-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0033_remove_weekdays_doctor_doctoruser_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='day',
        ),
        migrations.AddField(
            model_name='weekdays',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='doctors.doctoruser'),
        ),
    ]
